[project]
name = "astronomy_ml"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "sophia268238", email = "sophia268238@gmail.com"},
]
dependencies = [
    "pandas>=2.2.2",
    "keras>=3.2.1",
    "scipy>=1.13.0",
    "scikit-learn>=1.4.2",
    "ipython>=8.23.0",
    "ipykernel>=6.29.4",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "Apache-2.0 license"}


[tool.pdm]
distribution = false
